version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - '7000:7000'
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - myenv_dbHost=bolt://localhost:7474
      - myenv_dbUser=neo4j
      - myenv_dbPass=WHNMz7XG75AMWP34